import User1 from "@/public/Images/user1.png";
import User2 from "@/public/Images/user2.png";
import User3 from "@/public/Images/user3.png";
import Craving1 from "@/public/Images/craving1.png";
import Craving2 from "@/public/Images/craving2.png";
import Craving3 from "@/public/Images/craving3.png";

export const Users = [
  {
    id: "U1",
    userName: "FortuneNic",
    avatar: User1,
    friends: false,
    activeCravings: [
      {
        id: "AC1",
        image: Craving1,
        name: "Smokey Jollof with beef and Plantain",
        price: "6,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. yarnVivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 300,
        commentCount: 20,
        bookmarkCount: 100,
        mirrorCount: 100,
        comments: [
          {
            id: "C1",
            avatar: User2,
            userName: "thecraver256",
            comment: "I like this one",
            date: "2hr",
            liked: false,
            reply: [
              {
                id: "CR1",
                avatar: User3,
                userName: "Iyanu",
                comment: "Me too",
                date: "2hr",
                liked: false,
              },
            ],
          },
          {
            id: "C2",
            userName: "Pauleye",
            avatar: User3,
            comment: "Gbewaa oo",
            date: "June 7",
            liked: false,
            reply: [{}],
          },
          {
            id: "C3",
            avatar: User2,
            userName: "hungrybird132",
            comment: "Oh really",
            date: "June 7",
            liked: false,
            reply: [{}],
          },
        ],
      },
      {
        id: "AC2",
        image: Craving3,
        name: "Venum Boxing Gloves",
        price: "20,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 200,
        commentCount: 20,
        bookmarkCount: 70,
        mirrorCount: 30,
        comments: [
          {
            id: 1,
            avatar: User2,
            userName: "thecraver256",
            comment: "Who you wan dey box",
            date: "2hr",
            liked: false,
            reply: [
              {
                id: 1,
                avatar: User3,
                userName: "Iyanu",
                comment: "Mind Your business",
                date: "2hr",
                liked: false,
              },
            ],
          },
        ],
      },
      {
        id: "AC3",
        image: Craving2,
        name: "Samsung S23 Ultra - 512Gb",
        price: "800,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 300,
        commentCount: 20,
        bookmarkCount: 100,
        mirrorCount: 100,
        comments: [
          {
            id: 1,
            avatar: User2,
            userName: "thecraver256",
            comment: "I like this one",
            date: "2hr",
            liked: false,
            reply: [
              {
                id: 1,
                avatar: User3,
                userName: "Iyanu",
                comment: "Me too",
                date: "2hr",
                liked: false,
              },
            ],
          },
          {
            id: 2,
            userName: "Pauleye",
            comment: "I like this one",
            date: "June 7",
            liked: false,
            reply: [{}],
          },
        ],
      },
    ],
    satisfiedCravings: [
      {
        id: "SC1",
        image: Craving2,
        name: "Samsung S23 Ultra - 512Gb",
        price: "800,000",
        dateSatisfied: "June 7",
        anonymous: false,
        satisfier: "Stesy",
      },
    ],
  },
  {
    id: "U2",
    userName: "Pauleye",
    avatar: User2,
    friends: true,
    activeCravings: [
      {
        id: "AC1",
        image: Craving2,
        name: "Samsung S23 Ultra - 512Gb",
        price: "800,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 400,
        commentCount: 29,
        bookmarkCount: 273,
        mirrorCount: 40,
        comments: [
          {
            id: "C1",
            avatar: User1,
            userName: "thecraver256",
            comment: "Hehehe",
            date: "2hr",
            liked: false,
            reply: [],
          },
        ],
      },
      {
        id: "AC2",
        image: Craving3,
        name: "Venum Boxing Gloves",
        price: "20,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 200,
        commentCount: 20,
        bookmarkCount: 70,
        mirrorCount: 30,
        comments: [
          {
            id: "C1",
            avatar: User2,
            userName: "thecraver256",
            comment: "Who you wan dey box",
            date: "2hr",
            liked: false,
            reply: [
              {
                id: "CR1",
                avatar: User3,
                userName: "Iyanu",
                comment: "Mind Your business",
                date: "2hr",
                liked: false,
              },
            ],
          },
        ],
      },
    ],
    satisfiedCravings: [],
  },
  {
    id: "U3",
    userName: "Optimum",
    avatar: User3,
    friends: true,
    activeCravings: [
      {
        id: "AC1",
        image: Craving3,
        name: "Venum Boxing Gloves",
        price: "20,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 231,
        commentCount: 29,
        bookmarkCount: 73,
        mirrorCount: 40,
        comments: [
          {
            id: "C1",
            avatar: User1,
            userName: "thecraver256",
            comment: "Hehehe",
            date: "2hr",
            liked: false,
            reply: [],
          },
        ],
      },
    ],
    satisfiedCravings: [],
  },
  {
    id: "U4",
    userName: "Teepy",
    avatar: User1,
    friends: false,
    activeCravings: [
      {
        id: "AC1",
        image: Craving1,
        name: "Smokey Jollof with beef and Plantain",
        price: "6,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 300,
        commentCount: 20,
        bookmarkCount: 100,
        mirrorCount: 100,
        comments: [
          {
            id: "C1",
            avatar: User2,
            userName: "thecraver256",
            comment: "I like this one",
            date: "2hr",
            liked: false,
            reply: [
              {
                id: "CR1",
                avatar: User3,
                userName: "Iyanu",
                comment: "Me too",
                date: "2hr",
                liked: false,
              },
            ],
          },
          {
            id: "C2",
            userName: "Pauleye",
            comment: "Gbewaa oo",
            date: "June 7",
            liked: false,
            reply: [{}],
          },
          {
            id: "C3",
            userName: "hungrybird132",
            comment: "Oh really",
            date: "June 7",
            liked: false,
            reply: [{}],
          },
        ],
      },
      {
        id: "AC2",
        image: Craving3,
        name: "Venum Boxing Gloves",
        price: "20,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 200,
        commentCount: 20,
        bookmarkCount: 70,
        mirrorCount: 30,
        comments: [
          {
            id: 1,
            avatar: User2,
            userName: "thecraver256",
            comment: "Who you wan dey box",
            date: "2hr",
            liked: false,
            reply: [
              {
                id: 1,
                avatar: User3,
                userName: "Iyanu",
                comment: "Mind Your business",
                date: "2hr",
                liked: false,
              },
            ],
          },
        ],
      },
      {
        id: "AC3",
        image: Craving2,
        name: "Samsung S23 Ultra - 512Gb",
        price: "800,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 300,
        commentCount: 20,
        bookmarkCount: 100,
        mirrorCount: 100,
        comments: [
          {
            id: 1,
            avatar: User2,
            userName: "thecraver256",
            comment: "I like this one",
            date: "2hr",
            liked: false,
            reply: [
              {
                id: 1,
                avatar: User3,
                userName: "Iyanu",
                comment: "Me too",
                date: "2hr",
                liked: false,
              },
            ],
          },
          {
            id: 2,
            userName: "Pauleye",
            comment: "I like this one",
            date: "June 7",
            liked: false,
            reply: [{}],
          },
        ],
      },
    ],
    satisfiedCravings: [
      {
        id: "SC1",
        image: Craving2,
        name: "Samsung S23 Ultra - 512Gb",
        price: "800,000",
        dateSatisfied: "June 7",
        anonymous: false,
        satisfier: "Stesy",
      },
    ],
  },
  {
    id: "U5",
    userName: "OlaYK",
    avatar: User2,
    friends: true,
    activeCravings: [
      {
        id: "AC1",
        image: Craving2,
        name: "Samsung S23 Ultra - 512Gb",
        price: "800,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 400,
        commentCount: 29,
        bookmarkCount: 273,
        mirrorCount: 40,
        comments: [
          {
            id: "C1",
            avatar: User1,
            userName: "thecraver256",
            comment: "Hehehe",
            date: "2hr",
            liked: false,
            reply: [],
          },
        ],
      },
      {
        id: "AC2",
        image: Craving3,
        name: "Venum Boxing Gloves",
        price: "20,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 200,
        commentCount: 20,
        bookmarkCount: 70,
        mirrorCount: 30,
        comments: [
          {
            id: "C1",
            avatar: User2,
            userName: "thecraver256",
            comment: "Who you wan dey box",
            date: "2hr",
            liked: false,
            reply: [
              {
                id: "CR1",
                avatar: User3,
                userName: "Iyanu",
                comment: "Mind Your business",
                date: "2hr",
                liked: false,
              },
            ],
          },
        ],
      },
    ],
    satisfiedCravings: [],
  },
  {
    id: "U6",
    userName: "Optimum",
    avatar: User3,
    friends: true,
    activeCravings: [
      {
        id: "AC1",
        image: Craving3,
        name: "Venum Boxing Gloves",
        price: "20,000",
        craveNote:
          "Lorem ipsum dolor sit amet. Consectetur adipiscing elit. In a consectetur ante, quis luctus felis. Nunc scelerisque neque et pretium porttitor. Curabitur mollis molestie risus auctor dictum. Vivamus eleifend sodales felis, vitae consectetur turpis eleifend non. Ut gravida sem mauris, et sagittis dolor aliquet quis.",
        date: "June 7",
        liked: false,
        bookmarked: false,
        mirror: true,
        likeCount: 231,
        commentCount: 29,
        bookmarkCount: 73,
        mirrorCount: 40,
        comments: [
          {
            id: "C1",
            avatar: User1,
            userName: "thecraver256",
            comment: "Hehehe",
            date: "2hr",
            liked: false,
            reply: [],
          },
        ],
      },
    ],
    satisfiedCravings: [],
  },
];
